name: Test ref-exchange 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_ref_exchange:
    runs-on: ubuntu-latest 
    container:
      image: rust:1.56.1
      env:
        RUSTFLAGS: -C link-arg=-s
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update && apt-get install -y git less vim clang && \
          rustup toolchain install stable-2021-11-01 && \
          rustup default stable-2021-11-01 && \
          rustup target add wasm32-unknown-unknown && \
          make test
